WebClient_AP/Models/PersonalAccount.cs
using System;

#nullable disable

namespace WebClient_AP.Models
{
    public class PersonalAccount
    {
        public int IdAccount { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public string AppartmentId { get; set; }
        public double Square { get; set; }
        public DateTime? DateOpen { get; set; }
        public DateTime? DateClose { get; set; }
        public int? IdGroup { get; set; }
    }
}

WebClient_AP/Controllers/PersonalAccountController.cs
using Microsoft.AspNetCore.Mvc;
using WebClient_AP.Models;
using WebClient_AP.Models.View;

namespace WebClient_AP.Controllers
{
    public class PersonalAccountController : Controller
    {
        //get
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(PersonalAccount pa)
        {
            using (var client = new HttpClient())
            {
                pa.DateOpen = DateTime.Today;

                client.BaseAddress = new Uri("https://localhost:7288/api/PersonalAccount/Create");
                var createTask = client.PostAsJsonAsync("Create", pa);
                createTask.Wait();

                var resultCreate = createTask.Result;
                if (resultCreate.IsSuccessStatusCode)
                {
                    return RedirectToAction("List");
                }
                return View(pa);
            }
        }
        //get
        public IActionResult List()
        {
            IEnumerable<PersonalAccount>? accs = null;
            List<PersonalAccount_GroupVM> accsgr = new List<PersonalAccount_GroupVM>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7288/api/");
                var responseTask = client.GetAsync("PersonalAccount/Read");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var read = result.Content.ReadAsAsync<IList<PersonalAccount>>();
                    read.Wait();
                    accs = read.Result;
                    foreach (var acc in accs)
                    {
                        if (acc.IdGroup != null)
                        {
                            var quantity = client.GetAsync($"PersonalAccount/Quantity/{acc.IdGroup}");
                            quantity.Wait();
                            var resultQuantity = quantity.Result;
                            if (resultQuantity.IsSuccessStatusCode)
                            {
                                var count = resultQuantity.Content.ReadAsAsync<int>();
                                count.Wait();
                                var countResidents = count.Result;
                                PersonalAccount_GroupVM paVm = new PersonalAccount_GroupVM();
                                paVm.IdGroup = acc.IdGroup;
                                paVm.IdAccount = acc.IdAccount;
                                paVm.FirstName = acc.FirstName;
                                paVm.LastName = acc.LastName;
                                paVm.MiddleName = acc.MiddleName;
                                paVm.City = acc.City;
                                paVm.Street = acc.Street;
                                paVm.Building = acc.Building;
                                paVm.AppartmentId = acc.AppartmentId;
                                paVm.DateOpen = acc.DateOpen;
                                paVm.DateClose = acc.DateClose;
                                paVm.IdGroup = acc.IdGroup;
                                paVm.Quantity = countResidents;
                                accsgr.Add(paVm);
                            }
                            else
                            {
                                accs = null;
                                ModelState.AddModelError(String.Empty, "- Server error occured, List of Personal Accounts. Quantity -");
                            }
                        }
                        else
                        {
                            PersonalAccount_GroupVM paVm = new PersonalAccount_GroupVM();
                            paVm.IdGroup = acc.IdGroup;
                            paVm.IdAccount = acc.IdAccount;
                            paVm.FirstName = acc.FirstName;
                            paVm.LastName = acc.LastName;
                            paVm.MiddleName = acc.MiddleName;
                            paVm.City = acc.City;
                            paVm.Street = acc.Street;
                            paVm.Building = acc.Building;
                            paVm.AppartmentId = acc.AppartmentId;
                            paVm.DateOpen = acc.DateOpen;
                            paVm.DateClose = acc.DateClose;
                            paVm.IdGroup = acc.IdGroup;
                            paVm.Quantity = 0;
                            accsgr.Add(paVm);
                        }
                    }
                }
                else
                {
                    accs = null;
                    ModelState.AddModelError(String.Empty, "- Server error occured, List of Personal Accounts -");
                }
            }
            return View(accsgr);
        }
        //get
        public IActionResult ListSearch(string search)
        {
            IEnumerable<PersonalAccount>? accs = null;
            List<PersonalAccount_GroupVM> accsgr = new List<PersonalAccount_GroupVM>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7288/api/");
                var responseSearch = client.GetAsync("PersonalAccount/Read");
                responseSearch.Wait();

                var resultSearch = responseSearch.Result;

                if (resultSearch.IsSuccessStatusCode)
                {
                    var read = resultSearch.Content.ReadAsAsync<IList<PersonalAccount>>();
                    read.Wait();
                    accs = read.Result;
                    foreach (var acc in accs)
                    {
                        if (acc.IdGroup != null)
                        {
                            var quantity = client.GetAsync($"PersonalAccount/Quantity/{acc.IdGroup}");
                            quantity.Wait();
                            var resultQuantity = quantity.Result;
                            if (resultQuantity.IsSuccessStatusCode)
                            {
                                var count = resultQuantity.Content.ReadAsAsync<int>();
                                count.Wait();
                                var countResidents = count.Result;
                                PersonalAccount_GroupVM paVm = new PersonalAccount_GroupVM();
                                paVm.IdGroup = acc.IdGroup;
                                paVm.IdAccount = acc.IdAccount;
                                paVm.FirstName = acc.FirstName;
                                paVm.LastName = acc.LastName;
                                paVm.MiddleName = acc.MiddleName;
                                paVm.City = acc.City;
                                paVm.Street = acc.Street;
                                paVm.Building = acc.Building;
                                paVm.AppartmentId = acc.AppartmentId;
                                paVm.DateOpen = acc.DateOpen;
                                paVm.DateClose = acc.DateClose;
                                paVm.IdGroup = acc.IdGroup;
                                paVm.Quantity = countResidents;
                                accsgr.Add(paVm);
                            }
                            else
                            {
                                accs = null;
                                ModelState.AddModelError(String.Empty, "- Server error occured, List of Personal Accounts. Quantity -");
                            }
                        }
                        else
                        {
                            PersonalAccount_GroupVM paVm = new PersonalAccount_GroupVM();
                            paVm.IdGroup = acc.IdGroup;
                            paVm.IdAccount = acc.IdAccount;
                            paVm.FirstName = acc.FirstName;
                            paVm.LastName = acc.LastName;
                            paVm.MiddleName = acc.MiddleName;
                            paVm.City = acc.City;
                            paVm.Street = acc.Street;
                            paVm.Building = acc.Building;
                            paVm.AppartmentId = acc.AppartmentId;
                            paVm.DateOpen = acc.DateOpen;
                            paVm.DateClose = acc.DateClose;
                            paVm.IdGroup = acc.IdGroup;
                            paVm.Quantity = 0;
                            accsgr.Add(paVm);
                        }
                    }
                }
                else
                {
                    accs = null;
                    ModelState.AddModelError(String.Empty, "- Server error occured, List Search of Personal Accounts -");
                }
            }
            if (!string.IsNullOrWhiteSpace(search))
            {
                accsgr = accsgr.Where(x => x.FirstName.Contains(search) 
                                    || x.MiddleName.Contains(search)
                                    || x.LastName.Contains(search)
                                    || x.City.Contains(search)
                                    || x.Street.Contains(search)
                                    || x.Building.Contains(search)
                                    || x.AppartmentId.Contains(search)
                                    || x.DateOpen.ToString().Contains(search)
                                    || x.DateClose.ToString().Contains(search)).ToList();
            }
            return View(accsgr);
        }
        //get
        public IActionResult Details(int accId)
        {
            PersonalAccount? acc = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7288/api/");
                var responseTask = client.GetAsync($"PersonalAccount/Update/{accId}");
                responseTask.Wait();

WebClient_AP/Views/PersonalAccount/Create.cshtml
@model WebClient_AP.Models.PersonalAccount
@{
    ViewData["Title"] = "Create P.A.";
}
<h1>Create Personal Account</h1>

<h4>PersonalAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAccount"/>
            <input type="hidden" asp-for="IdGroup"/>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building" class="control-label"></label>
                <input asp-for="Building" class="form-control" />
                <span asp-validation-for="Building" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppartmentId" class="control-label"></label>
                <input asp-for="AppartmentId" class="form-control" />
                <span asp-validation-for="AppartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Square" class="control-label"></label>
                <input asp-for="Square" class="form-control" />
                <span asp-validation-for="Square" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="List" class="btn btn-outline-secondary mx-2 my-2">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebClient_AP/Views/PersonalAccount/Details.cshtml
@model WebClient_AP.Models.PersonalAccount

@{
    ViewData["Title"] = "Details of P.A.";
}

<h1>Details</h1>
<system.web>
    <globalization culture="ru-RU uiCulture="ru-RU" />
</system.web>
<h4>PersonalAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Details">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAccount" />
            <input type="hidden" asp-for="IdGroup" />
            <input type="hidden" asp-for="DateOpen" />
            <input type="hidden" asp-for="DateClose" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building" class="control-label"></label>
                <input asp-for="Building" class="form-control" />
                <span asp-validation-for="Building" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppartmentId" class="control-label"></label>
                <input asp-for="AppartmentId" class="form-control" />
                <span asp-validation-for="AppartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Square" class="control-label"></label>
                <input asp-for="Square" class="form-control" />
                <span asp-validation-for="Square" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary mx-2 my-2"/>
                <a asp-action="List" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebClient_AP/Views/PersonalAccount/List.cshtml
@model IList<WebClient_AP.Models.View.PersonalAccount_GroupVM>
@{
    ViewData["Title"] = "List of P.A.";
}
<div class="row pt-6">
    <div class="col">
        <h1>List of Personal Accounts</h1>
        <hr />
        @using (Html.BeginForm("ListSearch", "PersonalAccount", FormMethod.Get))
        {      
            <div class="form-group row">
                <div class="col d-flex justify-content-between">
                    <div class="col-4">
                        <input  type="text" class="form-control" placeholder="Input" name="search"/>
                    </div>
                    <div class="col mx-2"> 
                        <input type="submit" class="btn btn-primary" value="Search" id="btnSubmit"/> 
                    </div>
                    <div class="col-xs-2">
                        <a asp-action="Create" class=" btn btn-primary float-end" >Create New</a>
                    </div>
                </div>
            </div>
        }
    </div>
    <table class="table table-bordered table-striped my-2">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().IdAccount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().MiddleName)
                </th>
                <th>
                    Address
                </th>    
                <th>
                    @Html.DisplayNameFor(model => model.First().DateOpen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().DateClose)
                </th>
                <th>
                    Quantity of residents
                </th>
                <th>
                    Changes
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdAccount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MiddleName)
                    </td>
                    <td>
                        @item.City, @item.Street @item.Building, @item.AppartmentId
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOpen)
                    </td>
                    <td>
                        @if (item.DateClose == null)
                        {
                            @using (Html.BeginForm("CloseAP", "PersonalAccount", FormMethod.Post))
                            {
                                <input type="hidden" name="paVmID" value="@item.IdAccount"/>
                                <input type="submit" class="btn btn-outline-warning form-control" value="Close"/>
                            }
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.DateClose)
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        <div>
                            <a asp-action="Details" asp-route-accId="@item.IdAccount" class="btn btn-primary mx-2">Details</a>
                            <a asp-action="Residents" asp-route-accId="@item.IdAccount" class="btn btn-danger">Residents</a>
                        </div>
                    </td>
                </tr>
        }
        </tbody>
    </table>
</div>

WebClient_AP/Views/PersonalAccount/ListSearch.cshtml
@model IList<WebClient_AP.Models.View.PersonalAccount_GroupVM>
@{
    ViewData["Title"] = "List of P.A.";
}
<div class="row pt-6">
    <h1>List of Personal Accounts</h1>
    <hr />
    @using (Html.BeginForm("ListSearch", "PersonalAccount", FormMethod.Get))
    {    
        <div class="form-group row">
            <div class="col d-flex justify-content-between">
                <div class="col-4">
                    <input  type="text" class="form-control" placeholder="Input" name="search"/>
                </div>
                <div class="col mx-2"> 
                    <input type="submit" class="btn btn-primary" value="Search" id="btnSubmit"/> 
                </div>
                <div class="col-xs-2">
                    <a asp-action="Create" class="btn btn-primary float-end" >Create New</a>
                </div>
            </div>
        </div>
    }
    <table class="table table-bordered table-striped my-2">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().IdAccount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().MiddleName)
                </th>
                <th>
                    Address
                </th>    
                <th>
                    @Html.DisplayNameFor(model => model.First().DateOpen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().DateClose)
                </th>
                <th>
                    Quantity of residents
                </th>
                <th>
                    Changes
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdAccount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MiddleName)
                    </td>
                    <td>
                        @item.City, @item.Street @item.Building, @item.AppartmentId
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOpen)
                    </td>
                    <td>
                        @if (item.DateClose == null)
                        {
                            @using (Html.BeginForm("CloseAP", "PersonalAccount", FormMethod.Post))
                            {
                                <input type="hidden" name="paVmID" value="@item.IdAccount"/>
                                <input type="submit" class="btn btn-outline-warning" value="Close"/>
                            }
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.DateClose)
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        <div>
                            <a asp-action="Details" asp-route-accId="@item.IdAccount" class="btn btn-primary mx-2">Details</a>
                            <a asp-action="Residents" asp-route-accId="@item.IdAccount" class="btn btn-danger">Residents</a>
                        </div>
                    </td>
                </tr>
        }
        </tbody>
    </table>
</div>

WebClient_AP/Views/PersonalAccount/Residents.cshtml
@*@model WebClient_AP.Models.PersonalAccount*@
@model WebClient_AP.Models.View.PersonalAccount_Group_PersonVM
@{
    ViewData["Title"] = "Residents of P.A.";
}
<h1>Residents</h1>

<h4>PersonalAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Residents">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAccount" />
            <input type="hidden" asp-for="FirstName" />
            <input type="hidden" asp-for="LastName" />
            <input type="hidden" asp-for="MiddleName" />
            <input type="hidden" asp-for="City" />
            <input type="hidden" asp-for="Street" />
            <input type="hidden" asp-for="Building" />
            <input type="hidden" asp-for="AppartmentId" />
            <input type="hidden" asp-for="Square" />
            <input type="hidden" asp-for="DateOpen" />
            <input type="hidden" asp-for="DateClose" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary mx-2 my-2"/>
                <a asp-action="List" class="btn btn-secondary">Back to List</a>
            </div>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>
                                IdPerson
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Last_name
                            </th>
                            <th>
                                Middle_name
                            </th>
                            <th>
                                Date_since
                            </th>
                            <th>
                                Date_to
                            </th>
                            <th>
                                IsLiving
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for(int i = 0; i < Model.GroupPersons.Count; i++)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => modelItem.GroupPersons[i].IdPerson)
                                    <input hidden asp-for="@Model.GroupPersons[i].IdPerson"/>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => modelItem.GroupPersons[i].FirstName)
                                    <input hidden asp-for="@Model.GroupPersons[i].FirstName"/>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => modelItem.GroupPersons[i].LastName)
                                    <input hidden asp-for="@Model.GroupPersons[i].LastName"/>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => modelItem.GroupPersons[i].MiddleName)
                                    <input hidden asp-for="@Model.GroupPersons[i].MiddleName"/>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => modelItem.GroupPersons[i].DateSince)
                                    <input hidden asp-for="@Model.GroupPersons[i].DateSince"/>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => modelItem.GroupPersons[i].DateTo)
                                    <input hidden asp-for="@Model.GroupPersons[i].FirstName"/>
                                </td>
                                <td>
                                    @Html.CheckBoxFor(modelItem => modelItem.GroupPersons[i].isLiving)
                                </td>
                            </tr>
                        } 
                    </tbody>
                </table>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}